services:
  backend:
    build: .
    container_name: agentic-rag-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      CHROMA_PERSIST_DIRECTORY: "/app/data/chroma_db"
    volumes:
      - .:/app

  frontend:
    build: .
    container_name: agentic-rag-frontend
    command: streamlit run frontend/streamlit_app.py --server.port 8501 --server.enableCORS false
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: "http://backend:8000"
    depends_on:
      - backend
    volumes:
      - .:/app
